export default {
  namespaced: true,
  state: {
    meals: [
      {
        idMeal: "52771",
        strMeal: "Spicy Arrabiata Penne",
        strDrinkAlternate: null,
        strCategory: "Vegetarian",
        strArea: "Italian",
        strInstructions:
          "Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.",
        strMealThumb:
          "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
        strTags: "Pasta,Curry",
        strYoutube: "https://www.youtube.com/watch?v=1IszT_guI08",
        strIngredient1: "penne rigate",
        strIngredient2: "olive oil",
        strIngredient3: "garlic",
        strIngredient4: "chopped tomatoes",
        strIngredient5: "red chile flakes",
        strIngredient6: "italian seasoning",
        strIngredient7: "basil",
        strIngredient8: "Parmigiano-Reggiano",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strIngredient16: null,
        strIngredient17: null,
        strIngredient18: null,
        strIngredient19: null,
        strIngredient20: null,
        strMeasure1: "1 pound",
        strMeasure2: "1/4 cup",
        strMeasure3: "3 cloves",
        strMeasure4: "1 tin ",
        strMeasure5: "1/2 teaspoon",
        strMeasure6: "1/2 teaspoon",
        strMeasure7: "6 leaves",
        strMeasure8: "spinkling",
        strMeasure9: "",
        strMeasure10: "",
        strMeasure11: "",
        strMeasure12: "",
        strMeasure13: "",
        strMeasure14: "",
        strMeasure15: "",
        strMeasure16: null,
        strMeasure17: null,
        strMeasure18: null,
        strMeasure19: null,
        strMeasure20: null,
        strSource: null,
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
      {
        idMeal: "52795",
        strMeal: "Chicken Handi",
        strDrinkAlternate: null,
        strCategory: "Chicken",
        strArea: "Indian",
        strInstructions:
          "Take a large pot or wok, big enough to cook all the chicken, and heat the oil in it. Once the oil is hot, add sliced onion and fry them until deep golden brown. Then take them out on a plate and set aside.\r\nTo the same pot, add the chopped garlic and sauté for a minute. Then add the chopped tomatoes and cook until tomatoes turn soft. This would take about 5 minutes.\r\nThen return the fried onion to the pot and stir. Add ginger paste and sauté well.\r\nNow add the cumin seeds, half of the coriander seeds and chopped green chillies. Give them a quick stir.\r\nNext goes in the spices – turmeric powder and red chilli powder. Sauté the spices well for couple of minutes.\r\nAdd the chicken pieces to the wok, season it with salt to taste and cook the chicken covered on medium-low heat until the chicken is almost cooked through. This would take about 15 minutes. Slowly sautéing the chicken will enhance the flavor, so do not expedite this step by putting it on high heat.\r\nWhen the oil separates from the spices, add the beaten yogurt keeping the heat on lowest so that the yogurt doesn’t split. Sprinkle the remaining coriander seeds and add half of the dried fenugreek leaves. Mix well.\r\nFinally add the cream and give a final mix to combine everything well.\r\nSprinkle the remaining kasuri methi and garam masala and serve the chicken handi hot with naan or rotis. Enjoy!",
        strMealThumb:
          "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
        strTags: null,
        strYoutube: "https://www.youtube.com/watch?v=IO0issT0Rmc",
        strIngredient1: "Chicken",
        strIngredient2: "Onion",
        strIngredient3: "Tomatoes",
        strIngredient4: "Garlic",
        strIngredient5: "Ginger paste",
        strIngredient6: "Vegetable oil",
        strIngredient7: "Cumin seeds",
        strIngredient8: "Coriander seeds",
        strIngredient9: "Turmeric powder",
        strIngredient10: "Chilli powder",
        strIngredient11: "Green chilli",
        strIngredient12: "Yogurt",
        strIngredient13: "Cream",
        strIngredient14: "fenugreek",
        strIngredient15: "Garam masala",
        strIngredient16: "Salt",
        strIngredient17: "",
        strIngredient18: "",
        strIngredient19: "",
        strIngredient20: "",
        strMeasure1: "1.2 kg",
        strMeasure2: "5 thinly sliced",
        strMeasure3: "2 finely chopped",
        strMeasure4: "8 cloves chopped",
        strMeasure5: "1 tbsp",
        strMeasure6: "¼ cup",
        strMeasure7: "2 tsp",
        strMeasure8: "3 tsp",
        strMeasure9: "1 tsp",
        strMeasure10: "1 tsp",
        strMeasure11: "2",
        strMeasure12: "1 cup",
        strMeasure13: "¾ cup",
        strMeasure14: "3 tsp Dried",
        strMeasure15: "1 tsp",
        strMeasure16: "To taste",
        strMeasure17: "",
        strMeasure18: "",
        strMeasure19: "",
        strMeasure20: "",
        strSource: "",
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  },
  mutations: {
    setMeals(state, payload) {
      state.meals = payload;
    },
  },
  actions: {
    async searchMeals({ commit }, payload) {
      const res = await fetch(
        `https://www.themealdb.com/api/json/v1/1/search.php?s=${payload}`
      );
      const data = await res.json();

      commit("setMeals", data.meals);
    },
  },
  getters: {
    meals(state) {
      return state.meals;
    },
  },
};
